### ISSUE TITLE
Plugin makes hidden nylos reappear

### ISSUE THREAD

**Issue by Processhf** [InfernoStats/Nylo-Death-Indicators#2] opened 2022-10-01 02:18 UTC
Currently I'm experiencing a bug where the Nylos are hidden before the projectile hits them (as intended), but then they reappear 1 tick later and display their full death animation unhidden.

**Comment by InfernoStats** [comment] 2022-10-02 19:49
This was caused by a change in the NPC spawn/despawn code and now it appears that nylos "respawn" every single tick. I've pushed a fix for this and have requested a merge on the plugin-hub.

**Comment by JaccodR** [comment] 2022-10-05 17:13
It still seems broken, any update on this?

**Comment by nbulischeck** [comment] 2022-10-05 17:31
> It still seems broken, any update on this?

They haven't merged any plugin hub PRs for quite a while now.

**Comment by InfernoStats** [comment] 2023-01-29 20:38
This was fixed by RL reverting the original change.

**Closed as completed by InfernoStats** 2023-01-29 20:38 UTC
